---
title: "Introduction & Program Overview"
author: "Lindsey Dorson"
date: "2022-12-12"
output: html_document
---

## Introduction

The motivation for this evaluation is to analyze the success of the implementation of the Georgia HOPE Scholarship. HOPE stands for "Helping Outstanding Pupils Educationally," and Georgia Governor Zell Miller created it to address the lack of Georgia students attaining higher education [1]. The HOPE scholarship started in 1993 and was designed as a merit-based scholarship that rewards higher-achieving students. Accessing the success of such a scholarship program is important because higher education is pivotal to the economic success of any state. Therefore, this evaluation hopes to provide further insight into whether states should implement a statewide financial program like HOPE that can better support and prepare students for higher education.

## Program Overview

In Zell Miller's 1992 State of the State Address, he acknowledged that only 15% of Georgia students were graduating from college, which is way below the national average of 25% [2]. Therefore, HOPE was created with the goal of making college more accessible to Georgia students from low and middle-income families that desired to continue their education but couldn't combat rising tuition costs.

To receive financial aid, students were required to graduate from a Georgia high school with a B average and attend an in-state postsecondary institution. This requirement also hoped to persuade more Georgia students to remain in-state to boost enrollment.

Upon the implementation of the scholarship in 1993, eligible Georgia students were awarded tuition coverage for up to two years; however, that increased to four years within a year of being launched. Students were also required to maintain a 3.0 HOPE GPA at appropriate semester hour intervals in college to keep receiving the scholarship's financial assistance.

The Georgia Student Finance Commission (GSFC) administers the HOPE scholarship, which aligns with GSFC's mission to "promote and increase access to education for Georgians." The scholarship's financial awards are funded by the Georgia Lottery as well.

It is important to note that there have been many changes to the HOPE scholarship throughout the years, but this project focuses on its initial requirements and award amounts circa 1993.

## References

[1] "Hope." Georgia Student Finance Commission, <https://gsfc.georgia.gov/hope.> 

[2] Zell Miller on HOPE. YouTube, 7 Feb. 2012, <https://youtu.be/OPl8lHhasrQ.> Accessed 4 Nov. 2022.

\
